/**
 * Remove and recreate the generated artifact tree.
 *
 * Usage: node scripts/clean-dist.mjs
 */

import { mkdirSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { distDir } from './lib/repo-paths.mjs';

rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

writeFileSync(
  join(distDir, 'README.md'),
  [
    '# Generated artifacts',
    '',
    'This directory is regenerated by `npm run generate`.',
    'Edit the canonical source files under `data/` instead of editing files here by hand.'
  ].join('\n') + '\n'
);

console.log('  Cleaned: dist/');
